### ISSUE TITLE
Slow Pash performance in for loop with echo

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#382] opened 2021-11-15 10:42 UTC
Reproduce:
```sh
# write the code below to gen.sh
##############################
mkdir tmp_folder
for i in {0..2335}
do
    touch tmp_folder/$i.log
done
##############################
# write the code below to the run.sh
##############################
for i in tmp_folder/*
do
    echo $i
done
##############################
# generate the files
bash gen.sh
# and then execute using run.sh script
$PASH_TOP/pa.sh run.sh
```
In my machine, bash needs 0m0,016s whereas pa.sh needs 1m19,493s

Branch: future
Kernel: Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP x86_64 GNU/Linux
OS: Ubuntu 18.04.6 LTS (Bionic Beaver)
Machine: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

**Comment by angelhof** [comment] 2021-11-15 12:44
This is standard behavior. We have significantly improved the tight loop performance of PaSh but there are fundamental limits (the fact that every time we want to execute a command, we have to go through the process of compilation, reseting the state, etc. I am closing this issue for now since it is not a bug, and it cannot be addressed straightforwardly

**Closed by angelhof** 2021-11-15 12:44 UTC
Labels: bug

**Comment by dkarnikis** [comment] 2021-11-15 12:54
Could I re-structure this script somehow (using for-loops) to gain better performance using pash? 
Could you point me to these tight-loop examples that pash is compatible with?

**Comment by angelhof** [comment] 2021-11-15 13:02
By tight-loop performance improvement I meant that PaSh's performance has been improved in all loops in the last few months. However, it still cannot match the performance of plain bash in a loop of trivial commands since PaSh has to do a lot of stuff (e.g., state management) everytime it enters the body.

**Comment by angelhof** [comment] 2021-11-15 13:04
The only way to address this would be to not have loops with many iterations and trivial bodies. 

FYI there are plans to add some additional optimizations that can help in this case, but still, the performance won't be like bash's.

**Comment by dkarnikis** [comment] 2021-11-15 13:09
Alright, thanks. @tammam1998 @nvasilakis maybe you should take a look at this since it affects directly all our benchmarks.
